blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"  # Asegúrate de que este nombre sea correcto

urlpatterns = [
    path("", index, name="home"),
    path("add_post/", add_post, name="post"),
    path("add_categoryyyyy/", add_category, name="category"),
    path("details_post/<post_id>", details_post, name="details"),
    # path("search_post/", search_post, name="search"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    post = models.ForeignKey(Post, related_name="reviews", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentario de {self.name} en {self.post}"

blog/forms.py
from django import forms
from .models import Post, Review, Category


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description", "category"]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["name", "description"]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]


class SearchForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)


# class SearchForm(forms.Form):
#     q = forms.CharField(max_length=100, required=False, label="Buscar por título")
#     category = forms.ModelChoiceField(
#         queryset=Category.objects.all(), required=False, label="Categoría"
#     )

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Review, Category
from .forms import PostForm, ReviewForm, CategoryForm, SearchForm


def index(request):
    # Obtenemos los valores de los parámetros de búsqueda
    query = request.GET.get("title")
    category = request.GET.get("category")

    print(f"Valor de búsqueda: {query}")

    posts = Post.objects.all()

    # Filtramos por título si se ingresó una búsqueda
    if query:
        posts = posts.filter(title__icontains=query)
        if len(posts) == 0:
            posts = Post.objects.all()

    # Filtramos por categoría si se proporcionó un ID de categoría (entero)
    if category and category.isdigit():
        posts = posts.filter(category_id=category)

    posts = posts.order_by("-date")

    search_form = SearchForm()

    return render(request, "index.html", {"posts": posts, "search_form": search_form})


def add_post(request):
    if request.method == "POST":
        form_inst = PostForm(request.POST)
        if form_inst.is_valid():
            form_inst.save()
            return redirect("blog:home")
        else:
            print(form_inst.errors)
    else:
        form_show = PostForm()
        return render(request, "add_post.html", {"posts": form_show})


def add_category(request):
    if request.method == "POST":

        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:home")
        else:
            print(form.errors)
    else:
        formCategory = CategoryForm()
    return render(request, "add_category.html", {"formCategory": formCategory})


def details_post(request, post_id):
    one_posts = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        # print(request.method)
        reviews_form = ReviewForm(request.POST)
        if reviews_form.is_valid():
            # Crea una nueva reseña
            review = reviews_form.save(commit=False)
            review.post = one_posts  # Asocia la reseña con el post actual
            review.save()  # Guarda la reseña en la base de datos
            return redirect("blog:details", post_id=post_id)

    else:
        reviews_form = ReviewForm()

    # Obtiene todas las reseñas para el post actual
    reviews = one_posts.reviews.all()

    return render(
        request,
        "details_post.html",
        {"one_posts": one_posts, "reviews_form": reviews_form, "reviews": reviews},
    )


# def search_post(request):
#     posts = f"aca buscamos por titulo"
#     return render(request, "search_post.html", {"posts": posts})

blog/templates/add_category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="category-container">
    <h1 class="titulo-posts">Agregar Categoria</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ formCategory.as_p }}
        <button type="submit">Create Category</button>  
    </form>
</div>


{% endblock content %}

blog/templates/add_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="posts-container">
    <h1 class="titulo-posts">Create Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ posts.as_p }}
      <button type="submit">Save</button>
    </form>
    
</div>

{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tercera-Pre-Entrega-Fernandez</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
    <nav>
     
        <a href="/" class="title">Home</a>
     
     
     <ul>
        <li>
            <a href="{% url 'blog:post' %}"> Post </a>
        </li>
        <li>
            <a href="{% url 'blog:category' %}"> Categoria </a> 
        </li>
     </ul>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">pie de pagina</div>
</body>
</html>

blog/templates/details_post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<h1 class="details-posts-title">Post Details</h1>

<div class="detail-container">
   
    <div class="left">
        <div class="title-detail">{{one_posts.title}}</div>

        <div class="category-detail">Cateroria: {{one_posts.category}}</div>
        <div class="description-detail">
            <p>{{one_posts.description}}</p>
             
        </div>
        <div class="date-detail">Publicado: {{one_posts.date|date:'M d Y'}}</div> 
        <div class="add-reviews">
          
            <form action="" method="post" class="form-review">
                {% csrf_token %} 
                {{ reviews_form }}                
                <button type="submit">Comentar</button>
            </form>           
            
        </div>       
    </div>

    <div class="right">
      
        <div class="all-reviews">
            {% for x in reviews %}
               <div class="detail-card">
                   <h4>Usuario: {{x.name}}</h4>
                   <p class="descrip-detail">{{x.description}}</p>
                </div>

                
                {% endfor %}
            
        </div>
        
    </div>
   
   
        
</div>
        
    
    

{% endblock content %}

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<div class="titulo-blog">
   
    <div class="search-bar">
        <form method="GET" action=".">
            {{ search_form.as_p }}
            <button type="submit">Buscar</button>
        </form>
       
    </div>
</div>

<div class="index-container">
    
    {% for post in posts %}
    <div class="card">
        <h3>{{post.title}}</h3>
        <div class="containerCard">
            <p> Description: {{post.description|truncatechars:30 }}</p>
            <p> Category: {{post.category}}</p>
            <p>Date: {{post.date|date:'M d Y'}}</p>
        </div>

        <div class="botoneraCard">
            <a href="{% url 'blog:details' post.id %}">Details</a> 
            <span>{{ post.reviews.count }} Reviews</span>
        </div>
    </div>
        
    {% endfor %}
</div>
        
    
<!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In voluptatem sed soluta magnam nihil molestiae quisquam animi nulla numquam, laudantium, cupiditate ipsa. Placeat amet quisquam corporis unde sed non debitis assumenda ullam sapiente officiis! Voluptatem, dolorum recusandae sed vitae, tempora fugiat ea, vel modi illum architecto quidem quaerat reprehenderit debitis!</p>     -->

{% endblock content %}